Repository GonzaloUlla/unlp-dbd-newsler, pull requests merged in 2020-04, with the labels that each got.

#5 Issue#4: Fixing CNN and FoxNews Links
  news-crawler/spiders/cnn_spider.py
  news-crawler/spiders/fox_news_spider.py
  news-crawler/spiders/websites.py
Labels: bug

#7 Feature/sentiment_analysis to Master: Tweets sentiment, refactor, minor fixes
  news-crawler/Dockerfile
  news-crawler/cronjob
  news-crawler/spiders/websites.py
  requirements.txt
  twitter-crawler/Dockerfile
  twitter-crawler/cronjob
  twitter-crawler/requirements.txt
  twitter-crawler/scrapers/config.py
  twitter-crawler/scrapers/polling.py
  twitter-crawler/scrapers/sentiments.py
  twitter-crawler/scrapers/streaming.py
  twitter-crawler/scrapers/utils.py
Labels: enhancement

#10 Issues #9, #14 and #15: Setting elasticsearch indices correctly, Supervisord and Log Collection
  .gitignore
  docker-compose-ha.yml
  docker-compose.yml
  elk/elasticsearch-template-ha.json
  elk/elasticsearch-template.json
  elk/pipeline-ha/logstash-ha.conf
  elk/pipeline/logstash.conf
  news-crawler/Dockerfile
  news-crawler/cronjob
  news-crawler/entrypoint.sh
  news-crawler/filebeat.yml
  news-crawler/logrotate
  news-crawler/requirements.txt
  news-crawler/supervisor.conf
  requirements.txt
  twitter-crawler/Dockerfile
  twitter-crawler/cronjob
  twitter-crawler/entrypoint.sh
  twitter-crawler/filebeat.yml
  twitter-crawler/logrotate
  twitter-crawler/requirements.txt
  twitter-crawler/supervisor.conf
Labels: bug, enhancement

#17 Issue#11: Deprecating the individual spiders and updating documentation
  README.md
  news-crawler/run_spiders.sh
  news-crawler/spiders/al_jazeera_spider.py
  news-crawler/spiders/cnn_spider.py
  news-crawler/spiders/deutsche_welle_spider.py
  news-crawler/spiders/fox_news_spider.py
  news-crawler/spiders/the_guardian_spider.py
Labels: enhancement

#16 Issues #12: First dashboard
  README.md
  dashboards/v1_dashboard.ndjson
Labels: documentation, ui

#19 Issue/8 to Master: Closing Issues #8 and #18
  README.md
  docker-compose.yml
  elk/kibana-dashboard-v1.ndjson
  elk/logstash-entrypoint.sh
  news-crawler/entrypoint.sh
  twitter-crawler/entrypoint.sh
  twitter-crawler/examples/polling_retweeted_quote_input.json
  twitter-crawler/examples/polling_retweeted_quote_output.json
  twitter-crawler/examples/streaming_retweeted_quote_input.json
  twitter-crawler/examples/streaming_retweeted_quote_output.json
  twitter-crawler/scrapers/extractors.py
  twitter-crawler/scrapers/generators.py
  twitter-crawler/scrapers/polling.py
  twitter-crawler/scrapers/sentiments.py
  twitter-crawler/scrapers/streaming.py
  twitter-crawler/scrapers/utils.py
  twitter-crawler/supervisor.conf
  wait-for-it.sh
Labels: bug, enhancement

#25 Close #20: Add Data Dictionary
  README.md
Labels: documentation

#26 Added canvas
  README.md
  elk/kibana-canvas-v1.json
Labels: ui
